### ISSUE TITLE
TypeScript can't infer the type of `defineConfig`

### ISSUE THREAD

**Issue by SuperchupuDev** [sxzz/tsdown#26]
### Describe the bug

Exporting config with the format `export default defineConfig` makes TypeScript throw `The inferred type of 'default' cannot be named without a reference to './node_modules/tsdown/dist/options'. This is likely not portable. A type annotation is necessary. ts(2742)`. A workaround could be using a type annotation, but that's not possible due to the `Options` type not being exported

### Reproduction

https://pastebin.com/R7BspErm

### System Info

```Shell
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  Memory: 5.77 GB / 15.84 GB
Binaries:
  Node: 22.6.0 - ~\AppData\Local\fnm_multishells\12976_1723564053163\node.EXE
  npm: 10.8.2 - ~\AppData\Local\fnm_multishells\12976_1723564053163\npm.CMD
  pnpm: 9.6.0 - ~\AppData\Local\fnm_multishells\12976_1723564053163\pnpm.CMD
Browsers:
  Edge: Chromium (127.0.2651.74)
  Internet Explorer: 11.0.19041.4355
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed & released as `tsdown@0.2.6`
