### ISSUE TITLE
DTS Emit not updated in watch mode

### ISSUE THREAD

**Issue by lishaduck** [sxzz/tsdown#49]
### Describe the bug

In watch mode, updated dts don't get emitted.

### Reproduction

Stackblitz can't load Rolldown, so I'll just list steps:

- New tsdown project
- Start watch mode
- Edit a type
- DTS doesn't change

### System Info

```Shell
System:
    OS: macOS 14.7.1
    CPU: (8) arm64 Apple M1
    Memory: 126.39 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.10.0 - ~/.nvm/versions/node/v22.10.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.10.0/bin/npm
    Watchman: 2024.11.25.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1.1
```

### Used Package Manager

pnpm, npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Sadly, cannot reproduce. You can provide a reproduction repo on GitHub.

**Comment by lishaduck** [comment]
Ah, it's when `clean: true`: [`github:lishaduck/tsdown-repro`](https://github.com/lishaduck/tsdown-repro).

**Comment by sxzz** [comment]
Hmmm, in your reproduction repo the issue still cannot be reproduced.

**Comment by lishaduck** [comment]
> Hmmm, in your reproduction repo the issue still cannot be reproduced.

Hmm. I tried it again and it didn't repro it.
I did mess with options some more, and found that when editing the dts config (I added `extraOutdir: "types"`), it didn't move the files, but editing it (`./index.ts`) kept editing the original file (`./dist/index.ts`, rather than `./dist/types/index.ts`). Maybe I got stuck in some weirdness with that?

**Comment by lishaduck** [comment]
At this point, I'm closing this as can't repro, will reopen it if I can repro it (though the `extraOutdir` thing is weird and perhaps should be fixed?).

**Comment by fernandojbf** [comment]
From what I've seen, the issue with watch happens when TypeScript is used instead of oxc-transform. I'm on the latest version, but since I don't have isolatedDeclarations enabled, TypeScript is being used instead of oxc-transform. As a result, the .d.ts files don't update on each reload.

**Comment by jmlee2k** [comment]
I'm seeing the same behavior as @fernandojbf - once I enable `isolatedDeclarations`, the types are updated during watch mode.
