### ISSUE TITLE
Bundle types

### ISSUE THREAD

**Issue by lishaduck** [sxzz/tsdown#50]
### Clear and concise description of the problem

As a developer using tsdown, I'd like it if it emitted fewer files into dist.
Right now, if I export `index.ts` which exports `types.ts` and `type-syncer.ts`, it takes both files, but then `types.ts` imports `workspace-resolver.ts` (for some exported types), which gets bundled, but then `workspace-resolver` also exports some functions, which aren't used by `types.ts`, but are purely internal (to the app, not the file). Those functions take a globber, from `globber.ts`, which is nowhere used in the public api, but then it gets bundled, and so on.
In the end, a bunch of unused files are generated.

### Suggested solution

Run Rolldown over them (looks like it's planned, but isn't available yet)?

### Alternative

- [ ] Oxc emits them prebundled
- [ ] `unplugin-isolated-decl` bundled them
- [x] Ignore it, it's not a big deal.

### Additional context

"Clear and concise description of the problem" says that this is VueUse.

This isn't terribly important, more just a reminder for me to make sure to update tsdown once Rolldown offers something.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
- IIRC, I don't think Oxc or Rolldown currently has a pre-bundled dts feature, see #1388.
- `@microsoft/api-extractor` can bundle dts files. Eventually, I believe Rolldown will implement this feature, so there's no plan to integrate `@microsoft/api-extractor` with tsdown.

**Comment by sxzz** [comment]
I just asked the Rolldown team about this feature, and they have no plans for it at the moment. Here are some solutions we can consider:
- Integrate `@microsoft/api-extractor` with `unplugin-isolated-decl`.
- Or fork https://github.com/Swatinem/rollup-plugin-dts for Rolldown.

**Comment by lishaduck** [comment]
> I just asked the Rolldown team about this feature, and they have no plans for it at the moment.

I'm happy waiting assuming that "at the moment" means it still is planned for someday.

> Here are some solutions we can consider:
> 
> * Integrate `@microsoft/api-extractor` with `unplugin-isolated-decl`.
> * Or fork https://github.com/Swatinem/rollup-plugin-dts for Rolldown.

I'd prefer api-extractor _except_ that it only supports a single entrypoint.
`rollup-plugin-dts` is LGPL so we couldn't vendor it here as this is MIT, and it's in maintenance mode, but I guess if we wrote it in a separate repo (or just dealt with multiple licenses in a repo) then `unplugin-isolated-decl` could use it internally.
There's also `dts-bundle-generator`, but I don't think it provides anything over `rollup-plugin-dts`

**Comment by sxzz** [comment]
> I'm happy waiting assuming that "at the moment" means it still is planned for someday.

In the short term, there's no plan for it, but in the long term, they will eventually do it.

**Comment by sxzz** [comment]
We currently use Rollup with `rollup-plugin-dts` to bundle dts files. In the future, we hope to find a more efficient solution.

**Comment by sxzz** [comment]
That sounds great!

**Comment by subframe7536** [comment]
How about https://github.com/stacksjs/dtsx
